name: VUnit Test

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  verible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    container:
      image: ghcr.io/mluckydwyer/hw-ci:slim

    steps:
      - name: Run VUnit
        run: |
          find . -name "run.py" -print0 | xargs -0 -n1 python3
